import { Vehicle } from "./vehicle-showcase";

export const LAND_ROVER_INVENTORY: Vehicle[] = [
  {
    model: "Range Rover Sport",
    trim: "SE Dynamic",
    year: 2025,
    price: 89500,
    image: "/range-rover-sport.jpg",
    features: [
      "3.0L Mild Hybrid I6 Engine - 395 HP",
      "Dynamic Handling Pack",
      "Meridian Sound System",
      "Pivi Pro Infotainment",
      "Terrain Response 2",
      "Adaptive Cruise Control",
    ],
    available: true,
  },
  {
    model: "Range Rover",
    trim: "Autobiography",
    year: 2025,
    price: 139900,
    image: "/range-rover.jpg",
    features: [
      "4.4L Twin-Turbo V8 - 523 HP",
      "Executive Class Seating",
      "Meridian Signature Sound System",
      "All-Wheel Steering",
      "Air Suspension",
      "Panoramic Roof",
    ],
    available: true,
  },
  {
    model: "Defender 110",
    trim: "X-Dynamic SE",
    year: 2025,
    price: 71900,
    image: "/defender.jpg",
    features: [
      "3.0L Mild Hybrid I6 - 395 HP",
      "Configurable Terrain Response",
      "11.4-inch Touchscreen",
      "Wade Sensing",
      "ClearSight Ground View",
      "Roof Rails",
    ],
    available: true,
  },
  {
    model: "Discovery Sport",
    trim: "S R-Dynamic",
    year: 2025,
    price: 52900,
    image: "/discovery-sport.jpg",
    features: [
      "2.0L Turbocharged I4 - 246 HP",
      "5+2 Seating Configuration",
      "Terrain Response",
      "InControl Touch Pro",
      "Hands-Free Power Tailgate",
      "LED Headlights",
    ],
    available: true,
  },
  {
    model: "Range Rover Velar",
    trim: "P400 R-Dynamic S",
    year: 2025,
    price: 79900,
    image: "/velar.jpg",
    features: [
      "3.0L Supercharged V6 - 395 HP",
      "Touch Pro Duo Interface",
      "Matrix LED Headlights",
      "Configurable Dynamics",
      "Meridian Sound System",
      "Head-Up Display",
    ],
    available: false,
  },
];
